[project]
name = "stdio-server"
version = "0.1.0"
description = "FastMCP STDIO server with enhanced features"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastmcp==2.10.6", "mcp-shared"]

[tool.uv.sources]
mcp-shared = { workspace = true }
